#!/bin/sh
# inkVerb repo knight cron, verb.ink

# This updates the WordPress plugin and theme repos from the recepie sites at inkisaverb.com
## This is intended to be run as a chrontab job, so the recepie wp sites update automatically

# How to use:
## ./updatewpaddsite [wpadd namespace]

NAME=$1
PT=$2

# Include the config
. /var/local/ink/donjon/wpaddsites/wpaddrepo.cnf
. /var/local/ink/donjon/wpaddsites/wpadd.list

# Update -u recursive -r
cd /var/www/html/${NAME}${WPADDNAMESUFF}.${WPADDDOMAIN}/wp-content
rm -f /var/local/ink/repo/wp.${NAME}.zip

## Based on variables
if [ "${PT}" = "p" ]; then
zip -r /var/local/ink/repo/wp.${NAME}.zip plugins
fi
if [ "${PT}" = "t" ]; then
zip -r /var/local/ink/repo/wp.${NAME}.zip themes
fi
if [ "${PT}" = "pt" ]; then
zip -r /var/local/ink/repo/wp.${NAME}.zip plugins
zip -r /var/local/ink/repo/wp.${NAME}.zip themes
fi

