#!/bin/sh
# inkVerb repo donjon knight, verb.ink
set -e

# This updates the InfiniteWP-Admin repo package

# How to use:
## ./updaterepoiwpadmin [email address for registration]

# Eg:
## ./updaterepoiwpadmin dev@inkisaverb.com


# Check email is set
if [ -z $1 ]; then
echo "You must set an email for the repo package in InfiniteWP-Admin."
fi

IWPEMAIL=$1
CVAPPNAME=iwpadmin
# Include the repo versions
. /var/local/ink/configs/inklists/repoverlist
DISTVER="${iwpadmin}"

# Announce
echo "Updating the InfiniteWP-Admin package to v${DISTVER}..."
cd /var/local/ink/repo

# Get the package
curl -LO https://infinitewp.com/iwp-admin-panel-download.php?installedEmail=${IWPEMAIL}
# Fix the package
mv iwp-admin-panel-download.php?installedEmail=${IWPEMAIL} iwpadmin-${DISTVER}.zip
## Check the hash
### Every download is different, can't be checked
#CHECKSHA=$(shasum -a 256 iwpadmin-${DISTVER}.zip)
#if [ "${CHECKSHA}" = "${iwpadminsha}  iwpadmin-${DISTVER}.zip" ]; then
#echo "Download checks out."
#else
#echo "SHA check failed. The downloaded file is not what was expected. Did you set both the IWPAdmin version AND the IWPAdmin SHA per instructions?"
#exit 44
#fi

# Set it as the new package
rm -f ${CVAPPNAME}.legacy.zip
touch ${CVAPPNAME}.current.zip
mv ${CVAPPNAME}.current.zip ${CVAPPNAME}.legacy.zip
unzip iwpadmin-${DISTVER}.zip
rm iwpadmin-${DISTVER}.zip
mv IWPAdminPanel_v${DISTVER} ${CVAPPNAME}
zip -r ${CVAPPNAME}.current.zip ${CVAPPNAME}
rm -rf ${CVAPPNAME}

# Finish
echo "Done. This repo now has InfiniteWP-Admin v${DISTVER}."

